# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wILIXa1DMHGplhjdEGKcPzg9L_o3f7eq
"""

import streamlit as st

st.set_page_config(page_title="SmartSurvey", layout="centered")

st.markdown("""
<h2 style='text-align:center; color:#b30086;'>📊 SmartSurvey</h2>
<p style='text-align:center; font-size:16px;'>
Upload hasil survei kamu (.csv) dan dapatkan analisis otomatis dalam hitungan detik!
</p>
""", unsafe_allow_html=True)

uploaded_file = st.file_uploader("Unggah file hasil survei (.csv)", type=["csv"])

if uploaded_file is not None:
    st.success("File berhasil diunggah! Analisis otomatis akan segera tersedia.")